-- Drop table config_info_aggr
DROP TABLE config_info_aggr;

-- Add new table config_info_gray
CREATE TABLE config_info_gray (
    id bigint NOT NULL generated by default as identity,
    data_id varchar(255) NOT NULL,
    group_id varchar(128) NOT NULL,
    tenant_id varchar(128) default '',
    gray_name varchar(128) NOT NULL,
    gray_rule CLOB,
    app_name varchar(128),
    src_ip varchar(128),
    src_user varchar(128) default '',
    content CLOB,
    md5 varchar(32) DEFAULT NULL,
    encrypted_data_key varchar(32) DEFAULT NULL,
    gmt_create timestamp NOT NULL DEFAULT '2010-05-05 00:00:00',
    gmt_modified timestamp NOT NULL DEFAULT '2010-05-05 00:00:00',
    constraint configinfogray_id_key PRIMARY KEY (id),
    constraint uk_configinfogray_datagrouptenantgrayname UNIQUE (data_id,group_id,tenant_id,gray_name));

CREATE INDEX config_info_gray_dataid_gmt_modified ON config_info_gray(data_id,gmt_modified);
CREATE INDEX config_info_gray_gmt_modified ON config_info_gray(gmt_modified);

-- Support for gray release
ALTER TABLE his_config_info ADD publish_type varchar(50)  DEFAULT 'formal';
ALTER TABLE his_config_info ADD ext_info CLOB   DEFAULT NULL ;
ALTER TABLE his_config_info ADD gray_name varchar(128) DEFAULT NULL;