-- Drop table config_info_aggr
DROP TABLE config_info_aggr;

-- Add new table config_info_gray
CREATE TABLE config_info_gray (
    id NUMBER GENERATED BY DEFAULT AS IDENTITY,
    data_id VARCHAR2(255) NOT NULL,
    group_id VARCHAR2(128) NOT NULL,
    tenant_id VARCHAR2(128) DEFAULT '',
    gray_name VARCHAR2(128) NOT NULL,
    gray_rule CLOB,
    app_name VARCHAR2(128),
    src_ip VARCHAR2(128),
    src_user VARCHAR2(128) DEFAULT '',
    content CLOB,
    md5 VARCHAR2(32) DEFAULT NULL,
    encrypted_data_key VARCHAR2(32) DEFAULT NULL,
    gmt_create TIMESTAMP NOT NULL DEFAULT TO_DATE('2010-05-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    gmt_modified TIMESTAMP NOT NULL DEFAULT TO_DATE('2010-05-05 00:00:00', 'YYYY-MM-DD HH24:MI:SS'),
    CONSTRAINT configinfogray_id_key PRIMARY KEY (id),
    CONSTRAINT uk_configinfogray_datagrouptenantgrayname UNIQUE (data_id, group_id, tenant_id, gray_name)
);

CREATE INDEX config_info_gray_dataid_gmt_modified ON config_info_gray (data_id, gmt_modified);
CREATE INDEX config_info_gray_gmt_modified ON config_info_gray (gmt_modified);

-- Support for gray release
ALTER TABLE his_config_info ADD publish_type VARCHAR2(50) DEFAULT 'formal';
ALTER TABLE his_config_info ADD ext_info CLOB DEFAULT NULL;
ALTER TABLE his_config_info ADD gray_name VARCHAR2(128) DEFAULT NULL;